USE NoNameCoffeeBar;
GO

DELETE FROM SupplyReport;
DBCC CHECKIDENT('SupplyReport', RESEED, 0);

DELETE FROM BillReport;
DBCC CHECKIDENT('BillReport', RESEED, 0);

DELETE FROM FileData;
DBCC CHECKIDENT('FileData', RESEED, 0);

DELETE FROM BillStatus;
DBCC CHECKIDENT('BillStatus', RESEED, 0);

DELETE FROM BillContent;
DBCC CHECKIDENT('BillContent', RESEED, 0);

DELETE FROM Bill;
DBCC CHECKIDENT('Bill', RESEED, 0);

DELETE FROM Product;
DBCC CHECKIDENT('Product', RESEED, 0);

DELETE FROM Category;
DBCC CHECKIDENT('Category', RESEED, 0);

DELETE FROM UserData;
DBCC CHECKIDENT('UserData', RESEED, 0);

DELETE FROM UserType;
DBCC CHECKIDENT('UserType', RESEED, 0);
