USE master;
CREATE DATABASE NoNameCoffeeBar COLLATE Croatian_CI_AS_KS_WS;
GO
USE NoNameCoffeeBar;

CREATE TABLE UserType(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(20) NOT NULL,
	UNIQUE(Name)
);

CREATE TABLE UserData(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	UserName VARCHAR(20) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	FullName VARCHAR(50) NOT NULL,
	UserTypeId INT REFERENCES UserType(Id) NOT NULL,
	UNIQUE(UserName)
);

CREATE TABLE Category(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(20) NOT NULL,
	UNIQUE(Name)
);

CREATE TABLE Product(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	AvailableQuantity INT NOT NULL,
	Price FLOAT NOT NULL,
	CategoryId INT REFERENCES Category(Id) NOT NULL,
	UNIQUE(Name)
);

CREATE TABLE Bill(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	"Number" VARCHAR(15) NOT NULL,
	UNIQUE("Number")
);

CREATE TABLE BillContent(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	ProductPrice FLOAT NOT NULL,
	ProductQuantity INT NOT NULL,
	ProductId INT REFERENCES Product(Id) NOT NULL,
	BillId INT REFERENCES Bill(Id) NOT NULL
);

CREATE TABLE BillStatus(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(10) NOT NULL,
	StatusTimestamp DATETIME NOT NULL,
	BillId INT REFERENCES Bill(Id) NOT NULL
);

CREATE TABLE FileData(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	FileTimestamp DATETIME NOT NULL,
	ContentType VARCHAR(20) NOT NULL,
	"Data" TEXT NOT NULL,
	UNIQUE(Name)
);

CREATE TABLE BillReport(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	"Year" INT NOT NULL,
	"Month" INT NOT NULL,
	"Day" INT NOT NULL,
	FileDataId INT REFERENCES FileData(Id) NOT NULL
);

CREATE TABLE SupplyReport(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	"Year" INT NOT NULL,
	"Month" INT NOT NULL,
	"Day" INT NOT NULL,
	FileDataId INT REFERENCES FileData(Id) NOT NULL
);
